---
- name: Uninstall nginx from ubuntu
  hosts: ubuntu
  tasks:
   - name: stop nginx
     service:
        name: nginx
        state: stopped
   - name: uninstall nginx
      apt:
        name: nginx
        state: absent
        autoremove: true
        purge: true
